from q3 import Tracker
a = Tracker(9)
a.start("exam")
a.tick(3)
a.start("lunch")
a.tick(1)
a.stop("exam")
a.tick(1)
a.stop("lunch")
a.tick(1)
a.start("dance-class")
a.tick(1)
a.tick(1)
a.stop("dance-class")
a.tick(1)
a.start("meet-friends")
a.tick(4)
a.stop_all()
a.print_tasks()
