from q3 import *

def print_game(g):
    for p in [0,1]:
        print("".join([x or "_" for x in g.board[p]]))

random.seed(10)
game = Ur()
game.roll()
game.move(0)
game.roll()
game.move(0)
game.roll()
game.move(0) # warning printed here (target occupied)
game.move(2)
game.roll()
game.move(0)
game.roll()
game.move(0)
game.roll()
game.move(4) # warning printed here (no piece)
game.move(3)
game.roll()
game.move(0)
game.roll()
game.move(1)
game.roll()
game.pass_action()
game.roll()
game.move(0)
game.roll()
game.move(3) # other player piece it taken
game.roll()
game.move(0)
game.roll()
game.move(0)
game.roll()
game.move(1)
game.roll()
game.move(7)
game.roll()
game.move(0)
game.roll()
game.move(9)
game.roll()
game.move(4)
game.roll()
game.move(12) # arrived home
game.roll()
game.move(6)
print_game(game)
